export const data = [
  {
    ID: 1,
    Type: "Auditing",
    Name: "ONBOARDING",
    "Base Hours": (16 + 5 / 60),
    Description:
      "Kickstart your project with seamless setup of systems and processes for a productive start.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 1.1, Name: "Update Capsule", Hours: 0.17 },
      { ID: 1.2, Name: "GDrive Client Folder Setup", Hours: 0.17 },
      { ID: 1.3, Name: "PWF Setup", Hours: 0.25 },
      { ID: 1.4, Name: "Welcome Email Sent", Hours: 0.17 },
      { ID: 1.5, Name: "Kick Off Email Sent", Hours: 0.17 },
      { ID: 1.6, Name: "Internal Project Review", Hours: 0.25 },
      { ID: 1.7, Name: "Project & Communication Plan", Hours: 0.25 },
      { ID: 1.8, Name: "Discovery Meeting Set", Hours: 0.17 },
      { ID: 1.9, Name: "Pre-Discovery", Hours: 2.50 },
      { ID: 1.10, Name: "Discovery Meeting", Hours: 12 },
    ],
  },
  {
    ID: 2,
    Type: "Auditing",
    Name: "TECHNICAL AUDIT",
    "Base Hours": (12 + 35 / 60),
    Description:
      "Identify and resolve critical technical issues that might impact website conversion rate, establishing a reliable foundation for ongoing optimisation.",
    Inclusions: ["3 pages reviewed"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional page",
        Title: "Additional Pages",
        Hours_Per_Unit: 1,
        Description: "Adds additional page for review",
      },
    ],
    "Sub-tasks": [
      { ID: 2.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 2.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 2.3, Name: "Discovery Meeting", Hours: 1 },
      { ID: 2.4, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 2.5, Name: "Website Access", Hours: 0.5 },
      { ID: 2.6, Name: "GA Access", Hours: 0.25 },
      { ID: 2.7, Name: "AB Testing Platform Setup", Hours: 2 },
      { ID: 2.8, Name: "Technical Audit", Hours: 4 },
      { ID: 2.9, Name: "QA", Hours: 0.25 },
      { ID: 2.10, Name: "Presentation", Hours: 3 },
      { ID: 2.11, Name: "Follow Up and Notes", Hours: 0.5 },
      { ID: 2.12, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 3,
    Type: "Auditing",
    Name: "GOOGLE ANALYTIC AUDIT",
    "Base Hours": (11 + 5 / 60),
    Description:
      "Ensure Google Analytics is configured to provide truthful, correct, and reliable data, giving confidence in the insights used for testing and decision-making.",
    Inclusions: ["eCommerce Events or 3 Lead gen events"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional Lead Gen Event",
        Hours_Per_Unit: 0.5,
        Description: "Additional events to review",
      },
    ],
    "Sub-tasks": [
      { ID: 3.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 3.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 3.3, Name: "Discovery Meeting", Hours: 3 },
      { ID: 3.4, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 3.5, Name: "Website Access", Hours: 0.25 },
      { ID: 3.6, Name: "GA Access", Hours: 0.25 },
      { ID: 3.7, Name: "Analytics Audit", Hours: 4 },
      { ID: 3.8, Name: "QA", Hours: 0.5 },
      { ID: 3.9, Name: "Presentation", Hours: 0.5 },
      { ID: 3.11, Name: "Follow Up and Notes", Hours: 0.5 },
      { ID: 3.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 4,
    Type: "Auditing",
    Name: "BASELINE PERFORMANCE",
    "Base Hours": 18 + 35 / 60,
    Description:
      "Understand the performance of your website while identifying high-value audiences and key fallout areas.",
    Adjustments: [
      {
        Type: "fixed_increase",
        Condition: "specificTable",
        Hours_Increase: 3,
        Description: "Check to include additional segmented data",
      },
      {
        Type: "fixed_increase",
        Condition: "leadgenreport",
        Hours_Increase: 3,
        Description: "Check if the business is Lead Gen?",
      },
      {
        Type: "fixed_increase",
        Condition: "hybridwebsite",
        Hours_Increase: 2,
        Description: "Check if the website is hybrid",
      },
    ],
    "Sub-tasks": [
      { ID: 4.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 4.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 4.3, Name: "Pre-Discovery", Hours: 2 },
      { ID: 4.4, Name: "Website Access", Hours: 0.25 },
      { ID: 4.5, Name: "GA Access", Hours: 0.25 },
      { ID: 4.6, Name: "Discovery Meeting", Hours: 2 },
      { ID: 4.7, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 4.8, Name: "Baseline Performance Dashboard Creation", Hours: 8 },
      { ID: 4.9, Name: "QA", Hours: 1 },
      { ID: 4.11, Name: "Presentation", Hours: 3 },
      { ID: 4.12, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 4.13, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 6,
    Type: "Auditing",
    Name: "USER JOURNEY & DATA ANALYSIS",
    "Base Hours": 26 + 20 / 60,
    Description:
      "Analyse valuable audiences and critical website funnels to identify the specific stages at which users disengage from their journeys",
    Inclusions: ["Analysis of two valuable audiences"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional valuable audience",
        Hours_Per_Unit: 2,
        Description: "Adds additional valuable audience",
      },
    ],
    "Sub-tasks": [
      { ID: 6.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 6.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 6.3, Name: "Pre-Discovery", Hours: 4 },
      { ID: 6.4, Name: "GA Access", Hours: 0.25 },
      { ID: 6.5, Name: "Discovery Meeting", Hours: 2 },
      { ID: 6.6, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 6.7, Name: "User Journey & Data Analysis Execution", Hours: 16 },
      { ID: 6.8, Name: "QA", Hours: 1 },
      { ID: 6.9, Name: "Presentation", Hours: 3 },
      { ID: 6.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 6.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 7,
    Type: "Auditing",
    Name: "UX/UI REVIEW",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Identify UX/UI best practice violations based on Baymard’s 1080+ guidelines to address foundational usability issues",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 7.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 7.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 7.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 7.4, Name: "Discovery Meeting", Hours: 3 },
      { ID: 7.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 7.6, Name: "UX & UI Fundamental Review Execution", Hours: 8 },
      { ID: 7.7, Name: "QA", Hours: 1 },
      { ID: 7.8, Name: "Presentation", Hours: 1 },
      { ID: 7.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 7.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 8,
    Type: "Auditing",
    Name: "SEARCH & MERCH",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Guide users to the right product at the right time by analysing internal search and PLP merchandising to improve product findability, positioning and presentation",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 8.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 8.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 8.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 8.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 8.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 8.6, Name: "Search, Merchandise & Tech Audit Execution", Hours: 8 },
      { ID: 8.7, Name: "QA", Hours: 1 },
      { ID: 8.8, Name: "Presentation", Hours: 1 },
      { ID: 8.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 8.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 5,
    Type: "Auditing",
    Name: "CUSTOMER SURVEY & NPS",
    "Base Hours": 31.5,
        Inclusions: ["500 Responses Analysed", "2 Segments reviewed"],

    Description:
      "Uncover the underlying motivators and challenges that users encounter when considering and purchasing products from your website and brand, and receive exported responses",
    Adjustments: [{
        Type: "per_unit",
        Unit: "Additional Segment",
        Hours_Per_Unit: 2,
        Description: "Adds an additional segment ",
      },{
        Type: "per_unit",
        Unit: "Additional Question",
        Hours_Per_Unit: 1,
        Description: "Adds an additional question",
      },],
    "Sub-tasks": [
      { ID: 5.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 5.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 5.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 5.4, Name: "Discovery Meeting", Hours: 3 },
      { ID: 5.5, Name: "Survey Questions Drafted", Hours: 2 },
      { ID: 5.6, Name: "Survey Questions Approved", Hours: 0.08 },
      { ID: 5.7, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 5.8, Name: "Create survey in Survey Monkey", Hours: 2 },
      { ID: 5.9, Name: "Survey Approval & Updates", Hours: 0.08 },
      { ID: 5.10, Name: "Confirm Survey Sent", Hours: 0.17 },
      { ID: 5.11, Name: "Confirm Data Collected", Hours: 0.08 },
      { ID: 5.12, Name: "Survey Theming", Hours: 5 },
      { ID: 5.13, Name: "Survey Report", Hours: 10 },
      { ID: 5.14, Name: "NPS", Hours: 2 },
      { ID: 5.15, Name: "QA", Hours: 1 },
      { ID: 5.16, Name: "Presentation", Hours: 3 },
      { ID: 5.17, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 5.18, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 10,
    Type: "Auditing",
    Name: "SESSION RECORDING",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Analyze on-page user behaviour in recorded sessions to pinpoint friction points, reveal drop-off patterns, and uncover key factors contributing to low conversion rates, while gaining access to session recordings for direct review.",
    Inclusions: ["5 pages explored"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional page",
        Hours_Per_Unit: 2,
        Description: "Adds an additional page explored",
      },
    ],
    "Sub-tasks": [
      { ID: 10.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 10.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 10.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 10.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 10.5, Name: "Session Recording Tool Setup", Hours: 0.5 },
      { ID: 10.6, Name: "Session Recording Analysis", Hours: 4 },
      { ID: 10.7, Name: "Session Recording Report", Hours: 4 },
      { ID: 10.8, Name: "QA", Hours: 1 },
      { ID: 10.9, Name: "Presentation", Hours: 3 },
      { ID: 10.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 10.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 9,
    Type: "Auditing",
    Name: "USABILITY STUDIES",
    "Base Hours": 38 + 35 / 60,
    Description:
      "Conduct one-to-one interviews with website customers to observe their behaviour while performing both guided and non-guided tasks, validating hypotheses and uncovering hidden barriers.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 9.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 9.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 9.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 9.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 9.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 9.6, Name: "Screener Questions", Hours: 3 },
      { ID: 9.7, Name: "Usability Questions & Scenarios", Hours: 4 },
      { ID: 9.8, Name: "Questions & Scenario Approved", Hours: 0.5 },
      { ID: 9.9, Name: "Participant Recruitment (6 pax)", Hours: 5 },
      { ID: 9.10, Name: "Usability Sessions (6 pax)", Hours: 8 },
      { ID: 9.11, Name: "Usability Report", Hours: 8 },
      { ID: 9.12, Name: "QA", Hours: 1 },
      { ID: 9.13, Name: "Presentation/s", Hours: 3 },
      { ID: 9.14, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 9.15, Name: "Account Management", Hours: 2 },

    ],
    Variants: [
      {
        Name: "12 PAX",
        Hours_Increase: 9,
        Description: "Adds 9 hours for a study with 12 participants.",
      },
      {
        Name: "24 PAX",
        Hours_Increase: 19,
        Description: "Adds 19 hours for a study with 24 participants.",
      },
    ],
  },

  {
    ID: 11,
    Type: "Auditing",
    Name: "COMPETITOR REVIEW",
    "Base Hours": 17 + 35 / 60,
    Description:
      "Get a competitive edge with a deep dive into your rivals’ websites exposing their strengths and turning those insights into clear strategies to outsmart, outshine, and outsell them.",
    Inclusions: ["3 Competitors Reviewed"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional competitor",
        Hours_Per_Unit: 2,
        Description: "Add competitors",
      },
    ],
    "Sub-tasks": [
      { ID: 11.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 11.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 11.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 11.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 11.5, Name: "Competitor Review Execution", Hours: 8 },
      { ID: 11.6, Name: "QA", Hours: 1 },
      { ID: 11.7, Name: "Presentation", Hours: 3 },
      { ID: 11.8, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 11.9, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 12,
    Type: "Auditing",
    Name: "INFORMATION ARCHITECTURE",
    "Base Hours": 22 + 35 / 60,
    Description:
      "Analyse and optimise the structure, labeling, and hierarchy of the main and footer navigation to streamline user journeys, reduce friction, guide visitors to key pages more efficiently, and ultimately drive higher conversion rates.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 12.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 12.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 12.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 12.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 12.5, Name: "Card Sorting", Hours: 5 },
      { ID: 12.6, Name: "Information Architecture Development", Hours: 8 },
      { ID: 12.7, Name: "QA", Hours: 1 },
      { ID: 12.8, Name: "Presentation", Hours: 3 },
      { ID: 12.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 12.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 13,
    Type: "Auditing",
    Name: "CONVERSION REVIEW",
    "Base Hours": 26.58,
    Description:
      "Analyse your website using the MECLABS heuristic - enriched by years of research - to pinpoint exactly what’s blocking your conversions, and to create strategies to motivate users, incentivise actions, demonstrate value, and mitigate any friction or anxiety that may deter conversions. ",
    Inclusions: ["Two Personas Analysed", "Two User Journeys Analysed"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional persona",
        Hours_Per_Unit: 1,
        Description: "Add additional personas to analyse",
      },
      {
        Type: "per_unit",
        Unit: "additional user journey",
        Hours_Per_Unit: 1,
        Description: "Add additional user journey to analyse",
      },
    ],
    "Sub-tasks": [
      { ID: 13.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 13.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 13.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 13.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 13.5, Name: "Persona Creation", Hours: 3 },
      { ID: 13.6, Name: "User Journeys Mapping", Hours: 2 },
      { ID: 13.7, Name: "Conversion Review Analysis", Hours: 11 },
      { ID: 13.8, Name: "QA", Hours: 1 },
      { ID: 13.9, Name: "Presentation", Hours: 3 },
      { ID: 13.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 13.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 14,
    Type: "Strategy",
    Name: "STRATEGY",
    "Base Hours": 0.0,
    Description:
      "Prioritize digital experience improvements by categorizing insights, planning conversion goals, and creating a comprehensive, collaborative testing roadmap for quarterly optimization.",
    Adjustments: [],
    "Sub-tasks": [],
    Variants: [
      {
        Name: "Small Strategy",
        Monthly_Hours: 10,
        Description: "Included as part of execution under 12 months",
      },
      {
        Name: "Large Strategy",
        Monthly_Hours: 20,
        Description: "Included as part of execution 12 months or over",
      },

    ],
  },
  {
    ID: 15,
    Type: "Execution",
    Name: "EXECUTION",
    "Base Hours": 0,
    Description:
      "Ongoing CRO support: consistent ideation, testing, and analysis for sustainable growth based on commitment.",
    Adjustments: [],
    "Sub-tasks": [],
    Variants: [
      {
        Name: "6 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 6,
        Description: "6-month retainer, 40 hours per month",
      },
      {
        Name: "6 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 6,
        Description: "6-month retainer, 60 hours per month",
      },
      {
        Name: "6 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 6,
        Description: "6-month retainer, 80 hours per month",
      },

      {
        Name: "12 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 12,
        Description: "12-month retainer, 40 hours per month",
      },
      {
        Name: "12 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 12,
        Description: "12-month retainer, 60 hours per month",
      },
      {
        Name: "12 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 12,
        Description: "12-month retainer, 80 hours per month",
      },
      {
        Name: "24 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 24,
        Description: "24-month retainer, 40 hours per month",
      },
      {
        Name: "24 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 24,
        Description: "24-month retainer, 60 hours per month",
      },
      {
        Name: "24 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 24,
        Description: "24-month retainer, 80 hours per month",
      },
    ],
  },
];