export const data = [
  {
    ID: 1,
    Type: "Auditing",
    category: "Account & project management",
    Name: "ONBOARDING",
    displayName: "Onboarding",
    "Base Hours": (16 + 5 / 60),
    Description:
      "Kickstart your project with seamless setup of systems and processes for a productive start.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 1.1, Name: "Update Capsule", Hours: 0.17 },
      { ID: 1.2, Name: "GDrive Client Folder Setup", Hours: 0.17 },
      { ID: 1.3, Name: "PWF Setup", Hours: 0.25 },
      { ID: 1.4, Name: "Welcome Email Sent", Hours: 0.17 },
      { ID: 1.5, Name: "Kick Off Email Sent", Hours: 0.17 },
      { ID: 1.6, Name: "Internal Project Review", Hours: 0.25 },
      { ID: 1.7, Name: "Project & Communication Plan", Hours: 0.25 },
      { ID: 1.8, Name: "Discovery Meeting Set", Hours: 0.17 },
      { ID: 1.9, Name: "Pre-Discovery", Hours: 2.50 },
      { ID: 1.10, Name: "Discovery Meeting", Hours: 12 },
    ],
  },
  {
    ID: 2,
    Type: "Auditing",
    category: "Technical review",
    Name: "TECHNICAL AUDIT",
    displayName: "Technical audit",
    "Base Hours": (12 + 35 / 60),
    Description:
      "Identify and resolve critical technical issues that might impact website conversion rate, establishing a reliable foundation for ongoing optimisation.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 2.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 2.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 2.3, Name: "Discovery Meeting", Hours: 1 },
      { ID: 2.4, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 2.5, Name: "Website Access", Hours: 0.5 },
      { ID: 2.6, Name: "GA Access", Hours: 0.25 },
      { ID: 2.7, Name: "AB Testing Platform Setup", Hours: 2 },
      { ID: 2.8, Name: "Technical Audit", Hours: 4 },
      { ID: 2.9, Name: "QA", Hours: 0.25 },
      { ID: 2.10, Name: "Presentation", Hours: 3 },
      { ID: 2.11, Name: "Follow Up and Notes", Hours: 0.5 },
      { ID: 2.12, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 3,
    Type: "Auditing",
    category: "Data analysis",
    Name: "GOOGLE ANALYTIC AUDIT",
    displayName: "Google Analytics audit",
    "Base Hours": (11 + 5 / 60),
    Description:
      "Ensure Google Analytics is configured to provide truthful, correct, and reliable data, giving confidence in the insights used for testing and decision-making.",
    Adjustments: [
      {
        Type: "fixed_increase",
        Condition: "shopPaySupport",
        Hours_Increase: 1,
        Description: "ShopPay support",
      },
      {
        Type: "fixed_increase",
        Condition: "dataMismatch",
        Hours_Increase: 1,
        Description: "Data Mismatch",
      },
      {
        Type: "fixed_increase",
        Condition: "additionalTrackingLeadGen",
        Hours_Increase: 1,
        Description: "Additional Tracking for Lead Gen",
      },
    ],
    "Sub-tasks": [
      { ID: 3.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 3.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 3.3, Name: "Discovery Meeting", Hours: 3 },
      { ID: 3.4, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 3.5, Name: "Website Access", Hours: 0.25 },
      { ID: 3.6, Name: "GA Access", Hours: 0.25 },
      { ID: 3.7, Name: "Analytics Audit", Hours: 4 },
      { ID: 3.8, Name: "QA", Hours: 0.5 },
      { ID: 3.9, Name: "Presentation", Hours: 0.5 },
      { ID: 3.11, Name: "Follow Up and Notes", Hours: 0.5 },
      { ID: 3.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 4,
    Type: "Auditing",
    category: "Data analysis",
    Name: "BASELINE PERFORMANCE",
    displayName: "Baseline performance",
    "Base Hours": 18 + 35 / 60,
    Description:
      "Understand the performance of your website while identifying high-value audiences and key fallout areas.",
    Adjustments: [
      {
        Type: "exclusive_option",
        Condition: "baselineOption",
        Options: [
          { value: "ecommerce", label: "E-commerce", Hours_Increase: 3 },
          { value: "leadgen", label: "Lead Gen business", Hours_Increase: 3 },
          { value: "hybrid", label: "Website is hybrid", Hours_Increase: 2 },
        ],
      },
    ],
    "Sub-tasks": [
      { ID: 4.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 4.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 4.3, Name: "Pre-Discovery", Hours: 2 },
      { ID: 4.4, Name: "Website Access", Hours: 0.25 },
      { ID: 4.5, Name: "GA Access", Hours: 0.25 },
      { ID: 4.6, Name: "Discovery Meeting", Hours: 2 },
      { ID: 4.7, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 4.8, Name: "Baseline Performance Dashboard Creation", Hours: 8 },
      { ID: 4.9, Name: "QA", Hours: 1 },
      { ID: 4.11, Name: "Presentation", Hours: 3 },
      { ID: 4.12, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 4.13, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 6,
    Type: "Auditing",
    category: "Data analysis",
    Name: "USER JOURNEY & DATA ANALYSIS",
    displayName: "User journey & data analysis",
    "Base Hours": 26 + 20 / 60,
    Description:
      "Analyse valuable audiences and critical website funnels to identify the specific stages at which users disengage from their journeys",
    Inclusions: ["4 user journeys of 2 valuable audiences"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional valuable audience",
        Hours_Per_Unit: 2,
        Description: "Adds additional valuable audience",
      },
    ],
    "Sub-tasks": [
      { ID: 6.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 6.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 6.3, Name: "Pre-Discovery", Hours: 4 },
      { ID: 6.4, Name: "GA Access", Hours: 0.25 },
      { ID: 6.5, Name: "Discovery Meeting", Hours: 2 },
      { ID: 6.6, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 6.7, Name: "User Journey & Data Analysis Execution", Hours: 16 },
      { ID: 6.8, Name: "QA", Hours: 1 },
      { ID: 6.9, Name: "Presentation", Hours: 3 },
      { ID: 6.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 6.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 7,
    Type: "Auditing",
    category: "UX fundamentals",
    Name: "UX/UI REVIEW",
    displayName: "UX/UI review",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Identify UX/UI best practice violations based on Baymard’s 1080+ guidelines to address foundational usability issues",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 7.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 7.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 7.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 7.4, Name: "Discovery Meeting", Hours: 3 },
      { ID: 7.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 7.6, Name: "UX & UI Fundamental Review Execution", Hours: 8 },
      { ID: 7.7, Name: "QA", Hours: 1 },
      { ID: 7.8, Name: "Presentation", Hours: 1 },
      { ID: 7.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 7.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 8,
    Type: "Auditing",
    category: "UX fundamentals",
    Name: "SEARCH & MERCH",
    displayName: "Search & merch review",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Guide users to the right product at the right time by analysing internal search and PLP merchandising to improve product findability, positioning and presentation",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 8.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 8.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 8.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 8.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 8.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 8.6, Name: "Search, Merchandise & Tech Audit Execution", Hours: 8 },
      { ID: 8.7, Name: "QA", Hours: 1 },
      { ID: 8.8, Name: "Presentation", Hours: 1 },
      { ID: 8.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 8.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 5,
    Type: "Auditing",
    category: "Customer insights",
    Name: "CUSTOMER SURVEY & NPS",
    displayName: "Customer survey & NPS",
    "Base Hours": 31.5,
        Inclusions: ["500 Responses Analysed", "2 Segments reviewed"],

    Description:
      "Uncover the underlying motivators and challenges that users encounter when considering and purchasing products from your website and brand, and receive exported responses",
    Adjustments: [{
        Type: "per_unit",
        Unit: "Additional Segment",
        Hours_Per_Unit: 2,
        Description: "Adds an additional segment ",
      },{
        Type: "per_unit",
        Unit: "Additional Question",
        Hours_Per_Unit: 1,
        Description: "Adds an additional question",
      },],
    "Sub-tasks": [
      { ID: 5.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 5.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 5.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 5.4, Name: "Discovery Meeting", Hours: 3 },
      { ID: 5.5, Name: "Survey Questions Drafted", Hours: 2 },
      { ID: 5.6, Name: "Survey Questions Approved", Hours: 0.08 },
      { ID: 5.7, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 5.8, Name: "Create survey in Survey Monkey", Hours: 2 },
      { ID: 5.9, Name: "Survey Approval & Updates", Hours: 0.08 },
      { ID: 5.10, Name: "Confirm Survey Sent", Hours: 0.17 },
      { ID: 5.11, Name: "Confirm Data Collected", Hours: 0.08 },
      { ID: 5.12, Name: "Survey Theming", Hours: 5 },
      { ID: 5.13, Name: "Survey Report", Hours: 10 },
      { ID: 5.14, Name: "NPS", Hours: 2 },
      { ID: 5.15, Name: "QA", Hours: 1 },
      { ID: 5.16, Name: "Presentation", Hours: 3 },
      { ID: 5.17, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 5.18, Name: "Account Management", Hours: 2 },
    ],
  },
  {
    ID: 10,
    Type: "Auditing",
    category: "Customer insights",
    Name: "SESSION RECORDING",
    displayName: "Session recordings",
    "Base Hours": 18 + 5 / 60,
    Description:
      "Analyze on-page user behaviour in recorded sessions to pinpoint friction points, reveal drop-off patterns, and uncover key factors contributing to low conversion rates, while gaining access to session recordings for direct review.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 10.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 10.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 10.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 10.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 10.5, Name: "Session Recording Tool Setup", Hours: 0.5 },
      { ID: 10.6, Name: "Session Recording Analysis", Hours: 4 },
      { ID: 10.7, Name: "Session Recording Report", Hours: 4 },
      { ID: 10.8, Name: "QA", Hours: 1 },
      { ID: 10.9, Name: "Presentation", Hours: 3 },
      { ID: 10.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 10.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 9,
    Type: "Auditing",
    category: "Customer insights",
    Name: "USABILITY STUDIES",
    displayName: "Usability studies",
    "Base Hours": 38 + 35 / 60,
    Description:
      "Conduct one-to-one interviews with website customers to observe their behaviour while performing both guided and non-guided tasks, validating hypotheses and uncovering hidden barriers.",
    Adjustments: [],
    "Sub-tasks": [
      { ID: 9.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 9.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 9.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 9.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 9.5, Name: "Send Discovery Notes", Hours: 0.5 },
      { ID: 9.6, Name: "Screener Questions", Hours: 3 },
      { ID: 9.7, Name: "Usability Questions & Scenarios", Hours: 4 },
      { ID: 9.8, Name: "Questions & Scenario Approved", Hours: 0.5 },
      { ID: 9.9, Name: "Participant Recruitment (6 pax)", Hours: 5 },
      { ID: 9.10, Name: "Usability Sessions (6 pax)", Hours: 8 },
      { ID: 9.11, Name: "Usability Report", Hours: 8 },
      { ID: 9.12, Name: "QA", Hours: 1 },
      { ID: 9.13, Name: "Presentation/s", Hours: 3 },
      { ID: 9.14, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 9.15, Name: "Account Management", Hours: 2 },

    ],
    participantOptions: [
      { label: "6 participants", value: 6, hoursIncrease: 0 },
      { label: "12 participants", value: 12, hoursIncrease: 9 },
      { label: "24 participants", value: 24, hoursIncrease: 19 },
    ],
    Variants: [],
  },

  {
    ID: 11,
    Type: "Auditing",
    category: "Customer insights",
    Name: "COMPETITOR REVIEW",
    displayName: "Competitor review",
    "Base Hours": 17 + 35 / 60,
    Description:
      "Get a competitive edge with a deep dive into your rivals’ websites exposing their strengths and turning those insights into clear strategies to outsmart, outshine, and outsell them.",
    Inclusions: ["3 Competitors Reviewed"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional competitor",
        Hours_Per_Unit: 2,
        Description: "Add competitors",
      },
    ],
    "Sub-tasks": [
      { ID: 11.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 11.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 11.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 11.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 11.5, Name: "Competitor Review Execution", Hours: 8 },
      { ID: 11.6, Name: "QA", Hours: 1 },
      { ID: 11.7, Name: "Presentation", Hours: 3 },
      { ID: 11.8, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 11.9, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 12,
    Type: "Auditing",
    category: "Customer insights",
    Name: "INFORMATION ARCHITECTURE",
    displayName: "Information architecture",
    "Base Hours": 22 + 35 / 60,
    Description:
      "Analyse and optimise the structure, labeling, and hierarchy of the main and footer navigation to streamline user journeys, reduce friction, guide visitors to key pages more efficiently, and ultimately drive higher conversion rates.",
    Adjustments: [
      {
        Type: "exclusive_option",
        Condition: "pageHierarchy",
        Options: [
          { value: "1-50", label: "1–50 pages", Hours_Increase: 0 },
          { value: "50-99", label: "50–99 pages", Hours_Increase: 0 },
          { value: "100+", label: "100+ pages", Hours_Increase: 0 },
        ],
      },
    ],
    "Sub-tasks": [
      { ID: 12.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 12.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 12.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 12.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 12.5, Name: "Card Sorting", Hours: 5 },
      { ID: 12.6, Name: "Information Architecture Development", Hours: 8 },
      { ID: 12.7, Name: "QA", Hours: 1 },
      { ID: 12.8, Name: "Presentation", Hours: 3 },
      { ID: 12.9, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 12.11, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 13,
    Type: "Auditing",
    category: "Conversion",
    Name: "CONVERSION REVIEW",
    displayName: "Conversion review",
    "Base Hours": 26.58,
    Description:
      "Analyse your website using the MECLABS heuristic - enriched by years of research - to pinpoint exactly what’s blocking your conversions, and to create strategies to motivate users, incentivise actions, demonstrate value, and mitigate any friction or anxiety that may deter conversions. ",
    Inclusions: ["Two personas analysed"],
    Adjustments: [
      {
        Type: "per_unit",
        Unit: "additional persona",
        Hours_Per_Unit: 1,
        Description: "Two personas analysed",
      },
    ],
    "Sub-tasks": [
      { ID: 13.1, Name: "Discovery Document", Hours: 0.42 },
      { ID: 13.2, Name: "Discovery Agenda", Hours: 0.17 },
      { ID: 13.3, Name: "Pre-Discovery workshop", Hours: 2 },
      { ID: 13.4, Name: "Discovery Meeting", Hours: 2 },
      { ID: 13.5, Name: "Persona Creation", Hours: 3 },
      { ID: 13.6, Name: "User Journeys Mapping", Hours: 2 },
      { ID: 13.7, Name: "Conversion Review Analysis", Hours: 11 },
      { ID: 13.8, Name: "QA", Hours: 1 },
      { ID: 13.9, Name: "Presentation", Hours: 3 },
      { ID: 13.11, Name: "Follow Up and Notes", Hours: 1 },
      { ID: 13.12, Name: "Account Management", Hours: 2 },

    ],
  },
  {
    ID: 14,
    Type: "Strategy",
    category: "Strategy",
    Name: "TESTING PLAN",
    displayName: "Testing plan",
    "Base Hours": 10,
    Description:
      "Create a comprehensive testing roadmap that aligns experimentation efforts with business goals and conversion targets.",
    Adjustments: [],
    "Sub-tasks": [],
  },
  {
    ID: 16,
    Type: "Strategy",
    category: "Strategy",
    Name: "TEST PRIORITISATION",
    displayName: "Test prioritisation",
    "Base Hours": 8,
    Description:
      "Prioritize tests based on potential impact, implementation effort, and strategic business objectives to maximize ROI.",
    Adjustments: [],
    "Sub-tasks": [],
  },
  {
    ID: 17,
    Type: "Strategy",
    category: "Strategy",
    Name: "QUARTERLY PLAN",
    displayName: "Quarterly plan",
    "Base Hours": 10,
    Description:
      "Develop a quarterly optimization plan with clear milestones, deliverables, and measurable outcomes.",
    Adjustments: [],
    "Sub-tasks": [],
  },
  {
    ID: 18,
    Type: "Strategy",
    category: "Strategy",
    Name: "CROPRO DASHBOARD",
    displayName: "CROpro dashboard",
    "Base Hours": 5,
    Description:
      "Access to the CROpers dashboard for real-time performance tracking, reporting, and experiment management.",
    Adjustments: [],
    "Sub-tasks": [],
  },
  {
    ID: 15,
    Type: "Execution",
    category: "Experimentation",
    Name: "EXECUTION",
    displayName: "Execution",
    "Base Hours": 0,
    Description:
      "End to End CRO Execution with involvement from all departments",
    departments: [
      { name: "Strategy", icon: "/icons/execution/image 69.svg" },
      { name: "Data", icon: "/icons/execution/image 51.svg" },
      { name: "Customer experience", icon: "/icons/execution/image 58.svg" },
      { name: "Design", icon: "/icons/execution/image 54.svg" },
      { name: "Development", icon: "/icons/execution/image 67.svg" },
      { name: "Project management", icon: "/icons/execution/image 51-1.svg" },
      { name: "Technology", icon: "/icons/execution/image 50.svg" },
    ],
    Adjustments: [],
    "Sub-tasks": [],
    Variants: [
      {
        Name: "3 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 3,
        Description: "3-month retainer, 40 hours per month",
      },
      {
        Name: "3 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 3,
        Description: "3-month retainer, 60 hours per month",
      },
      {
        Name: "3 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 3,
        Description: "3-month retainer, 80 hours per month",
      },

      {
        Name: "6 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 6,
        Description: "6-month retainer, 40 hours per month",
      },
      {
        Name: "6 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 6,
        Description: "6-month retainer, 60 hours per month",
      },
      {
        Name: "6 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 6,
        Description: "6-month retainer, 80 hours per month",
      },
      {
        Name: "12 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 12,
        Description: "12-month retainer, 40 hours per month",
      },
      {
        Name: "12 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 12,
        Description: "12-month retainer, 60 hours per month",
      },
      {
        Name: "12 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 12,
        Description: "12-month retainer, 80 hours per month",
      },
      {
        Name: "24 Months @ 40 hrs/month",
        Monthly_Hours: 40,
        Duration_Months: 24,
        Description: "24-month retainer, 40 hours per month",
      },
      {
        Name: "24 Months @ 60 hrs/month",
        Monthly_Hours: 60,
        Duration_Months: 24,
        Description: "24-month retainer, 60 hours per month",
      },
      {
        Name: "24 Months @ 80 hrs/month",
        Monthly_Hours: 80,
        Duration_Months: 24,
        Description: "24-month retainer, 80 hours per month",
      },
    ],
  },
  {
    ID: 19,
    Type: "Execution",
    category: "Experimentation",
    Name: "RELATIONSHIP",
    displayName: "Relationship",
    "Base Hours": 0,
    Description:
      "Select the duration of your execution program. Longer commitments unlock greater retainer discounts.",
    durationOptions: [3, 6, 12, 24],
    Adjustments: [],
    "Sub-tasks": [],
  },
  {
    ID: 20,
    Type: "Technology",
    category: "Experimentation",
    Name: "OPTIMISATION SOFTWARE",
    displayName: "Optimisation software",
    "Base Hours": 0,
    fixedMonthlyCost: 0,
    Description:
      "AB testing and optimisation software tools for running experiments and tracking results.",
    softwareOptions: [
      { label: "Bring your own", value: "byo", monthlyCost: 0 },
      { label: "Varify", value: "varify", monthlyCost: 400 },
    ],
    Adjustments: [],
    "Sub-tasks": [],
  },
];